### ISSUE TITLE
Functionality Question...

### ISSUE THREAD

**Issue by patrickjquinn** [NemOry/Spo2fy#1]
Hey there!

You've long since abandoned this project I've no doubt BUT i'm digging through the source and modernizing it for 2020 and noticed something puzzling, you're pumping the preview URL into the MediaPlayer class rather than doing "proper" playback. I totally understand that this might have been done as a test measure whilst you built out the rest of the app but how did you intend to do this long term? 

I have a solution but it'll require a big chunk of work so I was hoping you might have another implementation which might have been more straight forward that I missed in the source for this?

Thanks for open sourcing this, its a massive leg up on building out a functional client :)

**Comment by lucascenir** [comment]
Hey, @patrickjquinn! Just wondering if you had any progress with the new implementation of the app.

**Comment by oliverbytes** [comment]
> Hey there!
> 
> You've long since abandoned this project I've no doubt BUT i'm digging through the source and modernizing it for 2020 and noticed something puzzling, you're pumping the preview URL into the MediaPlayer class rather than doing "proper" playback. I totally understand that this might have been done as a test measure whilst you built out the rest of the app but how did you intend to do this long term?
> 
> I have a solution but it'll require a big chunk of work so I was hoping you might have another implementation which might have been more straight forward that I missed in the source for this?
> 
> Thanks for open sourcing this, its a massive leg up on building out a functional client :)

Hi Patrick! My bad for the super late response. You're free to clone this repo and do whatever you'd like. 👍
